[package]
name = "tdlib-tl-gen"
version = "0.1.0"
authors = ["Marco Melorio <marco.melorio@protonmail.com>"]
edition = "2021"

[dependencies]
tdlib-tl-parser = { path = "../tdlib-tl-parser", version = "0.1" }
